kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: node
  commands:
  - npm ci
  - npm run build
- name: deploy
  image: appleboy/drone-scp
  settings:
    host: openssh-server.files
    username: jcm
    password:
      from_secret: ssh_password
    port: 2222
    target: /config/data/chocoboard
    source: build/
    strip_components: 1
  when:
    event:
    - promote
    target:
    - production
