steps:
  build:
    image: node
    commands:
      - yarn install --frozen-lockfile
      - yarn run build
  deploy:
    image: appleboy/drone-scp
    settings:
      host: openssh-server.files
      username: jcm
      key:
        from_secret: ssh_key
      port: 2222
      target: /config/data/chocoboard
      source: dist/
      strip_components: 1
    when:
      - environment: production
      - event: deployment
